atlassian/react-sweet-state

- babel.config.js
- examples/advanced-flow/index.js
- examples/advanced-scoped-flow/index.js
- examples/basic-flow/index.js
- examples/performance-test/index.js
- package-lock.json
- package.json
- src/defaults.js
If `babel-polyfill` is imported after `sweet-state`, `middlewares` will be undefined as IE11 does not support `Set` by default. 
The solution is lazy init the `Set` the first time `middlewares` is accessed, so it will work regardless the import order.
> Ensure IE11 support

- src/middlewares/index.js
Not a major change, it seems like it's a small waste to reverse -> reduce, reduceRight should do the same thing.
> use reduceRight to simplify applyMiddleware

- examples/advanced-flow/components/user/actions.js
- src/store/__tests__/bind-actions.test.js
- src/store/bind-actions.js
`bindAction` was receiving the object with the original actions instead of the bound ones.
Interestingly, Container was already passing the bound actions to onInit and onUpdate but only on the first action. Now it works recursively and everywhere.
> Fix nested actions not bound

- docs/basics/hook.md
- docs/basics/subscriber.md
Correcting the omission of `getState` in the params of two code examples.
> Minor hook + subscriber docs correction

- docs/_sidebar.md
- docs/index.html
This PR supersedes the 404 fix PR: https://github.com/atlassian/react-sweet-state/pull/20
Changes introduced:
- configuration for relativePath set to true. _Now all links can be set as relative to the context they are rendered in (../../....) or in an aboslute manner (/blah/baha -> base/#/blah/baha)_
- links in the sidebar have been set to absolute given the sidebar is rendered under multiple contexts
> docs(): fix relative linking

- package-lock.json
- package.json
* Removed `docsify-cli` from dev deps, now using `npx` in npm script because there's no telling when that is going to get patched
> Fixes docsify-cli security vulnerabilities

- src/components/__tests__/hook.test.js
- src/components/hook.js
The actual call to update might be deferred and executed after component unmount has been called (like in case of batched updates). So before setting state we ensure the subscription is still live.
> Ensure state is not updated after unmount

- src/components/__tests__/hook.test.js
- src/components/__tests__/integration.test.js
- src/components/hook.js
Found an unexpected behaviour of React `act()` in tests: it automatically batch updates. Which caused the integration tests that where assessing the subscription call order to pass even if actual update order was wrong!
So I've removed `act()` wrapping on those tests to ensure they still fail when the subscription update order is wrong. 
Also reverting some recent changes on the hook implementation (mainly subscription on mount/update) as subscription update was wrong too.
> Fix updates batched in tests

- README.md
- docs/advanced/README.md
- docs/advanced/actions.md
- docs/advanced/mutator.md
- docs/api/actions.md
- types/index.d.ts
Current TS type definition does not allow customisation of `setState` to accomodate a custom mutator. By using an interface we can overload `setState` definition tu allow custom arguments (like a function).
I've also relaxed the types of the default mutator so TS does not complain on the actual implementation of it and `setState` can be called with anything.
> Add custom mutator docs and types fix

- src/components/__tests__/container.test.js
- src/components/container.js
Looks like enzyme still hasn't proper support for `contextType`, breaking components on shallow rendering + dive. See https://github.com/airbnb/enzyme/issues/1553
> Fix globalRegistry being undefined with enzyme shallow

- types/index.d.ts
Hi, I've just found this in my code and thought that it mind be helpful to other as well.
```ts
type ActionAny<TState, TContainerProps = void, TReturnValue = any> = (
api: StoreActionApi<TState>,
containerProps: TContainerProps
) => TReturnValue;
```
Should be BC, because it is a last arg and defaults to original type value.
> Update ActionAny to be more generic

- src/__tests__/types.flow.js
- src/index.js.flow
- types/index.d.ts
- types/test.tsx
Non object shapes were never really supported and behaved weirdly. This enforces it at type level.
Closes #70
> Enforce store type to be object

- src/components/__tests__/hook.test.js
- src/components/hook.js
Returning a function is quite bad as will invalidate memoisation on every state update, yet currently it breaks as `useState` will execute that function on hook mount. By switching to lazy `useState` we can store the selector output into the state even if that is itself a function.
> Fix selector returning a function

- babel.config.js
- src/index.js
- src/utils/__tests__/batched-updates.test.js
- src/utils/batched-updates.js
- src/utils/batched-updates.native.js
- src/utils/schedule.js
Change `batch` export implementation to schedule if `batchedUpdates` is `true` and avoid nested schedules to waterfall.
> Fix nested batch scheduling

- src/utils/__tests__/shallow-equal.test.js
- src/utils/shallow-equal.js
Current `shallowEqual` does not flag complex objects as changed, making selectors not trigger re-renders in valid cases. 
Fixes #175
> Ensure shallowEqual bails out for complex objects

- docs/_sidebar.md
Not sure whether the page that this item links to was removed intentionally and this was just missed in the clean-up.
> remove link to missing 'performance tips' page

- README.md
- docs/README.md
- docs/basics/store.md
Update Docs to note that store name, if provided should be unique.
**Context**
We ran into a bug where we had multiple stores with the same name and initial state, which caused a clash and unexpected behaviour. This doesn't fix the underlying problem but it does note that store name should be unique which solves the issue if anyone else runs into this.
> Docs: Add note about store name being unique to avoid clashes

- src/enhancers/__tests__/devtools.test.js
- src/enhancers/devtools.js
Redux devtools has a `trace` functionality that allows to see the action callstack (if source code is compiled properly).
Closes #181 as helps locating the actual `dispatch` line
> Enable devtools trace by default

- docs/api/store.md
- src/components/__tests__/integration.test.js
- src/components/container.js
- src/store/registry.js
The new Store API, `containedBy`, allows us to signal whenever a store is being used in global context but the creator intended it to be used behind a container. 
This is especially helpful to detect leaking stores, where the UI might still work but the data accidentally will be retained in the global space.
Closes #190
> Throw error when not contained

- src/__tests__/integration.test.js
- src/components/__tests__/container.test.js
- src/components/container.js
- src/components/hook.js
- src/context.js
- src/store/__tests__/bind-actions.test.js
- src/store/__tests__/registry.test.js
- src/store/bind-actions.js
- src/store/registry.js
A couple of minor improvements to help future developments (eg #201 ):
- refactor `bindActions` arguments and `dispatch` 
- rename `context.getStore` to `retrieveStore` to clarify API difference from `registry.getStore`
- throw sync containedBy errors if env does not support scheduling (eg jsdom) 
- refactor getStore options to be easier to expand
There should be no public API changes as all this is internal stuff or unreleased
> Refactor dispatch and getStore naming

- docs/api/container.md
- docs/api/store.md
- src/__tests__/integration.test.js
- src/components/__tests__/container.test.js
- src/components/__tests__/hook.test.js
- src/components/container.js
- src/components/hook.js
- src/store/registry.js
- types/index.d.ts
- types/test.tsx
Fix a couple of regressions with the container implementation:
- new implementation did not fire `onInit` on every mount with override mode (current expected behaviour)
- call new `onContainerUpdate` with next/prev props as arguments
- fix `onContainerUpdate` being called continuously and generating re-render loops
- fix a bug on hook store subscription not picking up new subscription on scope change if oldState == newState
> Fix onContainerUpdate and override compat

- src/components/__tests__/container.test.js
- src/components/container.js
The new Container implementation is lazy by default (does not create a store until a subscriber asks for it) but current implementation allows container to be mounted as sibling to initialise global stores.
So we add a test to ensure we still support this use case. That also found another scenario where `isGlobal` stores might get cleaned up accidentally
> Support childless global containers pattern

- src/__tests__/integration.test.js
- src/components/__tests__/container.test.js
- src/components/container.js
Legacy implementation contains a potential memory leak and we don't need it anymore.
> Remove legacy container implementation
