docs/_sidebar.md
It was teasing my OCD syndrom ;)
=> Fix Typo in the docs sidebar

docs/basics/store.md
=> Fix typo in docs

src/index.js.flow
=> Expose more Flow types

docs/README.md, docs/advanced/actions.md, docs/advanced/container.md, docs/advanced/devtools.md, docs/advanced/middlewares.md, docs/advanced/rehydration.md, docs/advanced/selector.md, docs/api/actions.md, docs/api/container.md, docs/api/store.md, docs/api/subscriber.md, docs/basics/actions.md, docs/basics/hook.md, docs/basics/store.md, docs/basics/subscriber.md, docs/introduction/motivation.md, docs/recipes/composition.md, docs/recipes/flow.md
- Typos
- Re-phrasing a few things
- Minor code fixes
- Hydration docs chapter 🥳
=> docs(review): general review of existing docs

docs/_sidebar.md, docs/advanced/actions.md, docs/testing/README.md, docs/testing/actions.md
- simple actions
- async actions
- composed actions
- note of caution
=> docs(issue-26): Documentation for action testing

src/components/__tests__/integration.test.js, src/components/hook.js, src/components/subscriber.js, src/middlewares/index.js
https://codesandbox.io/s/frosty-snowflake-heun8?fontsize=14
=> fix subscriptions not following react tree order

src/index.js.flow, types/index.d.ts
=> Fix types of instance actions

docs/testing/actions.md
I found a few typos in the actions test example doc so I thought I'd pay it forward and raise a PR to update 😄
=> Fix typos in the actions test example docs

examples/advanced-scoped-flow/index.html, examples/basic-flow/index.html
Minor house keeping fix on support material to correct titles of example code.
=> Fix example code page titles

docs/advanced/actions.md, docs/advanced/container.md, docs/advanced/rehydration.md, docs/advanced/selector.md, docs/api/actions.md, docs/api/hook.md, docs/api/subscriber.md, docs/basics/actions.md, docs/basics/hook.md, docs/basics/subscriber.md, docs/introduction/comparison.md, docs/introduction/motivation.md, docs/recipes/flow.md, docs/recipes/typescript.md, docs/testing/actions.md
Polishing the docs by fixing existing spelling mistakes and making some minor corrections to the sentence phrasing
=> Docs cleanup and minor corrections

docs/advanced/middlewares.md, examples/advanced-flow/components/todo/index.js, examples/advanced-flow/components/user/index.js, examples/advanced-flow/index.js, examples/advanced-scoped-flow/views/chat-rpc.js, package-lock.json, package.json, src/__tests__/mocks.js, src/__tests__/types.flow.js, src/components/__tests__/hook.test.js, src/components/__tests__/integration.test.js, src/components/container.js, src/components/hook.js, src/enhancers/__tests__/devtools.test.js, src/index.js, src/index.js.flow, src/middlewares/batch.js, src/middlewares/index.js, src/store/__tests__/create-state.test.js, src/store/create-state.js, src/utils/batched-updates.js, src/utils/batched-updates.native.js, types/index.d.ts, types/test.tsx
Given Redux is also batching updates by default, I would consider the API stable enough. It also delivers some small perf improvements (on top of making sweet-state `StrictMode` compatible).
Closes #77
=> Batch updates by default and support strict mode

src/components/__tests__/integration.test.js, src/middlewares/update.js
=> Ensure state is shallow checked

docs/basics/actions.md
The current code example is incorrect, this corrects it.
=> docs(actions): correct code examples

docs/testing/actions.md
Hello!
I've been reading your docs and I noticed that one example should be changed and another should use parentheses for consistency.
=> Docs update

docs/README.md
=> docs: fix typo

babel.config.js, examples/advanced-flow/components/todo/actions.js, examples/advanced-flow/components/todo/index.js, examples/advanced-flow/components/user/actions.js, examples/advanced-flow/components/user/index.js, examples/advanced-scoped-flow/components/form.js, examples/advanced-scoped-flow/components/messages.js, examples/advanced-scoped-flow/components/theme.js, examples/basic-flow/components.js, examples/basic-ts/components.tsx, examples/performance-scale-test/controllers/todos.js, examples/performance-test/components/todos.js, src/components/__tests__/container.test.js, src/components/container.js, src/defaults.js, src/index.js.flow, src/store/bind-actions.js, src/utils/batched-updates.js, types/index.d.ts
- Change default schedule profile to be immediate
- Remove IE11 Set workaround
- Deprecate actions Flow type and print a warning when accessed
- Fix StoreState.key type
=> Deprecated actions and fix StoreState.key type

docs/advanced/selector.md, docs/api/hook.md, docs/basics/hook.md, docs/recipes/composition.md, docs/recipes/flow.md, examples/advanced-flow/components/user/index.js, examples/advanced-flow/views/todo-list.js, examples/advanced-scoped-flow/components/messages.js, examples/advanced-scoped-flow/views/chat-hook.js, src/__tests__/types.flow.js, src/components/__tests__/hook.test.js, src/components/hook.js, src/index.js, src/index.js.flow, types/index.d.ts, types/test.tsx
New `createActionsHook` and `createStateHook` APIs
Closes #145
=> Add createActionsHook and createStateHook

types/index.d.ts
Closes #164 
Please note that this is my first time ever contributing to someone's else project. I might miss something...
And my main programming is in C#, neither ts nor js...
=> Fix container not having 'children' in it's props

src/components/__tests__/container.test.js, src/components/container.js
Due to the async nature of cleanup, we ensure registry `deleteStore` is called only if the Container store instance has not been replaced in meantime.
Closes #193
=> Fix store cleanup race condition

src/__tests__/mocks.js, src/components/__tests__/container.test.js, src/components/container.js, src/store/create-state.js
=> Improve performance of subscribe/unsubscribe in store
